MvcDemo/Models/Code.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Code
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "代码名称")]
        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "代码名称长度在2位到20位之间。")]
        public string Name { get; set; }
        [Display(Name = "代码类型")]
        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "代码类型长度在2位到20位之间。")]
        public string Type { get; set; }
        [Display(Name = "是否可用")]
        [Required]
        public string Memo { get; set; }
    }
}

MvcDemo/Controllers/CodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDemo.Models;
using System.Data.Entity;
using System.Data;

namespace MvcDemo.Controllers
{
    public class CodeController : Controller
    {
        //
        // GET: /Code/
        private htgisEntities1 db = new htgisEntities1();

        public ActionResult Index()
        {
            ViewBag.id = "d";
            return View(db.Code.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Code st)
        {
            db.Code.Add(st);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {
            Code stt = db.Code.Find(Id);
            db.Code.Remove(stt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id = 0)
        {

            Code st = db.Code.Find(id);
            if (st == null)
            {
                return HttpNotFound();
            }

            return View(st);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Code st)
        {
            if (ModelState.IsValid)
            {


                db.Entry(st).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(st);
        }
    }
}

MvcDemo/Views/Code/Create.cshtml
@model MvcDemo.Models.Code

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>创建</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>创建代码</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Memo)
            </div>
            <div class="editor-field">
                @Html.CheckBox("Memo",true)
                @Html.ValidationMessageFor(model => model.Memo)
            </div>
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MvcDemo/Views/Code/Edit.cshtml
@model MvcDemo.Models.Code

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>修改</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>修改</legend>
    
            @Html.HiddenFor(model => model.Id)
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Memo)
            </div>
            <div class="editor-field">
                @if (Model.Memo == "true")
                {
                    <p>@Html.CheckBox("Memo", true)</p>
                }
                else
                {
                    <p>@Html.CheckBox("Memo", false)</p>
                }
                @Html.ValidationMessageFor(model => model.Memo)
            </div>
    
            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MvcDemo/Views/Code/Index.cshtml
@model IEnumerable<MvcDemo.Models.Code>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>代码管理</title>
    <style type="text/css">
        #tbList {
            border: 1px solid #0094ff;
            width: 600px;
            margin: 10px auto;
            border-collapse: collapse;
        }

            #tbList th, td {
                border: 1px solid #0094ff;
                padding: 10px;
            }

        .tds {
            border: none;
            padding: 5px;
        }
    </style>
    <script type="text/javascript">
    function del(Id)
    {
        if (confirm("是否删除?"))
        {

            eval("document.all.d" + Id + ".click()");
        }
    }
    </script>

    </head>
    <body>
        <p>
            @Html.ActionLink("新建代码", "Create")
        </p>
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Memo)
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Memo)
                </td>
                <td>
                    @Html.ActionLink("修改", "Edit", new { id=item.Id }) |
                  
                    <a href="#" target="_self" onclick="del('@item.Id')">删除</a>
                    @using (Html.BeginForm("Delete", "Code", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <span style="display:none">

                            @Html.TextBox("Id", item.Id)
                            <input type="submit" id="@ViewBag.id@item.Id.ToString()" value="Delete" />
                        </span>
                }
                </td>
            </tr>
    }

        </table>
    </body>
    </html>