MvcDemo/Models/ExaminationInformation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class ExaminationInformation
    {
        [Key]
        [Required]
        public int Id { get; set; }
        public int StudentId { get; set; }
        [Display(Name = "学科")]
        [Required]
        public int Discipline { get; set; }
        [Display(Name = "考试时间")]
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime ExaminationTime { get; set; }
        [Display(Name = "成绩")]
        [Required]
        [Range(1, 150)]
        public int Fraction { get; set; }

        public virtual StudentInformation StudentInformation { get; set; }
    }
}

MvcDemo/Controllers/ExaminationInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDemo.Models;
using System.Data.Entity;
using System.Data;

namespace MvcDemo.Controllers
{
    public class ExaminationInformationController : Controller
    {
        //
        // GET: /ExaminationInformation/
        private htgisEntities1 db = new htgisEntities1();
        /// <summary>
        /// 加载学生分数
        /// </summary>
        /// <param name="Id">学生信息表的ID对应成绩表的StudentId</param>
        /// <returns></returns>
        public ActionResult Index(int Id)
        {
            ViewBag.cid = "d";
            ViewBag.id = Id;
            //因为需要级联学生名所以新建EIList实体
            IQueryable<EIList> AdList = from a in db.ExaminationInformation
                                        from b in db.Code
                                        where
                                          a.Discipline == b.Id && a.StudentId==Id
                                          orderby
                                        a.ExaminationTime,
                                        a.Discipline
                                        select new EIList
                                        {
                                            Id=a.Id,
                                            StudentId=a.StudentId,
                                            DisciplineName=b.Name,
                                            ExaminationTime=a.ExaminationTime,
                                            Fraction=a.Fraction
                                        };
            //查找学生名
            var name = from StudentInformation in db.StudentInformation
                       where
                         StudentInformation.Id == Id
                       select new
                       {
                           StudentInformation.Name
                       };
            ViewBag.name = name.ToList()[0].Name;
            return View(AdList.ToList());
        }
        /// <summary>
        /// 创建成绩
        /// </summary>
        /// <param name="id">ExaminationInformation中的唯一标识</param>
        /// <returns></returns>
        public ActionResult Create(int id)
        {
            ViewBag.id = id;
            var name = from StudentInformation in db.StudentInformation
                       where
                         StudentInformation.Id == id
                       select new
                       {
                           StudentInformation.Name
                       };
            ViewBag.name = name.ToList()[0].Name;
            var dcode = from Code in db.Code
                        where
                          Code.Type == "学科"
                        orderby
                          Code.Name
                        select new
                        {
                            Code.Name,
                            Code.Id
                        };
            ViewBag.DisciplineCode = new SelectList(dcode, "Id", "Name");
            ExaminationInformation st = new ExaminationInformation();
            st.Discipline = 5;
            st.StudentId=id;
            st.ExaminationTime = System.DateTime.Now;
            return View(st);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExaminationInformation st)
        {
            db.ExaminationInformation.Add(st);
            db.SaveChanges();
            return RedirectToAction("Index/"+st.StudentId);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {
            var st = from m in db.ExaminationInformation
                                        where m.Id == Id
                                        select m;
            ExaminationInformation stt = st.ToList()[0];
            db.ExaminationInformation.Remove(stt);
            db.SaveChanges();
            return RedirectToAction("Index/" + stt.StudentId);
        }
        public ActionResult Details(int Id)
        {

            ViewBag.id = Id;
            IQueryable<EIList> AdList = from a in db.ExaminationInformation
                                        from b in db.Code
                                        where
                                          a.Discipline == b.Id && a.Id == Id
                                        orderby
                                      a.ExaminationTime,
                                      a.Discipline
                                        select new EIList
                                        {
                                            Id = a.Id,
                                            StudentId = a.StudentId,
                                            DisciplineName = b.Name,
                                            ExaminationTime = a.ExaminationTime,
                                            Fraction = a.Fraction
                                        };
            int studentId=AdList.ToList()[0].StudentId;
            var name = from StudentInformation in db.StudentInformation
                       where
                         StudentInformation.Id == studentId
                       select new
                       {
                           StudentInformation.Name
                       };
            ViewBag.name = name.ToList()[0].Name;
            EIList st = new EIList();

            if (AdList.Count() > 0)
            {
                st = AdList.ToList()[0];
            }
            else
            {
                return HttpNotFound();
            }
            return View(st);
        }

        public ActionResult Edit(int Id = 0)
        {
            var dcode = from Code in db.Code
                        where
                          Code.Type == "学科"
                        orderby
                          Code.Name
                        select new
                        {
                            Code.Name,
                            Code.Id
                        };
            ViewBag.DisciplineCode = new SelectList(dcode, "Id", "Name");
            var st = from m in db.ExaminationInformation
                     where m.Id == Id
                     select m;
            ExaminationInformation stt = st.ToList()[0];
            int studentId = stt.StudentId;
            ViewBag.studentId = studentId;
            var name = from StudentInformation in db.StudentInformation
                       where
                         StudentInformation.Id == studentId
                       select new
                       {
                           StudentInformation.Name
                       };
            ViewBag.name = name.ToList()[0].Name;
            if (stt == null)
            {
                return HttpNotFound();
            }

            return View(stt);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExaminationInformation st)
        {
            if (ModelState.IsValid)
            {


                db.Entry(st).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index/"+st.StudentId);
            }
            return View(st);
        }
    }
}

MvcDemo/Controllers/StudentInformationController.cs
using MvcDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;
using MvcDemo.CS;

namespace MvcDemo.Controllers
{
    public class StudentInformationController : Controller
    {
        //
        // GET: /StudentInformation/
        private htgisEntities1 db = new htgisEntities1();
        /// <summary>
        /// 学生信息加载
        /// </summary>
        /// <param name="Dp">系别</param>
        /// <param name="SearchString">姓名</param>
        /// <returns>默认显示全部</returns>
        [MemberValidation]
        public ActionResult Index(string Dp, string SearchString)
        {
            //查询代码表系别分类并赋值给View的系别DropDownList
            var Dp1 = from d in db.Code
                       where 
                     d.Type=="系别"
                           orderby d.Name                         
                           select new
                           {
                               d.Name
                           };


            ViewBag.Dp = new SelectList(Dp1,"Name","Name");

            //将linq查询内容赋给非数据库实体类
            IQueryable<STList>  AdList = from a in db.StudentInformation
                     from b in db.Code
                     where
                       a.Department == b.Id
                     orderby
                       b.Name,
                       a.Name
                               select new STList
                     {
                         Id=a.Id,
                         Name=a.Name,
                         Sex=a.Sex,
                         DepartmentName = b.Name,
                         EntranceTime=a.EntranceTime
                     };
            //由于ID是数字所以生成删除等按钮时input的ID位数字会发生找不到的问题。
            ViewBag.id = "d";
            //判读是否有查询条件
            if (!String.IsNullOrEmpty(SearchString))
            {
                AdList = AdList.Where(s => s.Name.Contains(SearchString));
            }
            //判读是否有查询条件
            if (string.IsNullOrEmpty(Dp))
                return View(AdList.ToList());
            else
            {
                return View(AdList.Where(x => x.DepartmentName == Dp));
            }

           // return View(AdList.ToList());
        }
        /// <summary>
        /// 创建
        /// </summary>
        /// <returns></returns>
        [MemberValidation]
        public ActionResult Create()
        {
            //查询代码表系别分类并赋值给View的系别DropDownList
            var dcode = from Code in db.Code
                        where
                          Code.Type == "系别"
                        orderby
                          Code.Name
                        select new
                        {
                            Code.Name,
                            Code.Id
                        };
            //设置 DropDownList的VALUE和TEXT
            ViewBag.DepartmentCode = new SelectList(dcode, "Id", "Name");

            //设置默认值
            StudentInformation st = new StudentInformation();
            st.Sex = "1";
            st.Department = 1;
            st.EntranceTime = System.DateTime.Now;
            return View(st);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentInformation st)
        {
            db.StudentInformation.Add(st);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {
            StudentInformation st = db.StudentInformation.Find(Id);
            db.StudentInformation.Remove(st);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// 详细信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {

            IQueryable<STList> AdList = from a in db.StudentInformation
                                        from b in db.Code
                                        where
                                          a.Department == b.Id && a.Id==id
                                        orderby
                                          b.Name,
                                          a.Name
                                        select new STList
                                        {
                                            Id = a.Id,
                                            Name = a.Name,
                                            Sex = a.Sex,
                                            DepartmentName = b.Name,
                                            EntranceTime = a.EntranceTime
                                        };
           STList st = new STList();
          
           if (AdList.Count() > 0)
           {
               st = AdList.ToList()[0];
           }
           else
           {
               return HttpNotFound();
           }
            return View(st);
        }
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="id">学生信息的唯一ID值</param>
        /// <returns></returns>
        public ActionResult Edit(int id = 0)
        {
            //查询代码表系别分类并赋值给View的系别DropDownList
            var dcode = from Code in db.Code
                        where
                          Code.Type == "系别"
                        orderby
                          Code.Name
                        select new
                        {
                            Code.Name,
                            Code.Id
                        };
            ViewBag.DepartmentCode = new SelectList(dcode, "Id", "Name");
            StudentInformation st = db.StudentInformation.Find(id);
            if (st == null)
            {
                return HttpNotFound();
            }
            
            return View(st);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StudentInformation st)
        {
            if (ModelState.IsValid)
            {

                
                    db.Entry(st).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
            }
            return View(st);
        }
    }
}

MvcDemo/Views/ExaminationInformation/Create.cshtml
@model MvcDemo.Models.ExaminationInformation

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.name 成绩添加</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>@ViewBag.name 成绩添加</legend>
    
            <div style="display:none">
                @Html.LabelFor(model => model.StudentId)
            </div>
            <div style="display:none">
                @Html.EditorFor(model => model.StudentId)
                @Html.ValidationMessageFor(model => model.StudentId)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Discipline)
            </div>
            <div class="editor-field">
               @Html.DropDownListFor(model => model.Discipline, ViewBag.DisciplineCode as IEnumerable<SelectListItem>, new { @style = "width:150px;" })
                @Html.ValidationMessageFor(model => model.Discipline)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ExaminationTime)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ExaminationTime)
                @Html.ValidationMessageFor(model => model.ExaminationTime)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Fraction)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Fraction)
                @Html.ValidationMessageFor(model => model.Fraction)
            </div>
    
            <p>
                <input type="submit" value="提交" />
            </p>
        </fieldset>
    }
    
    <div>
        <a target="_self" href="../Index/@ViewBag.id">返回成绩列表</a>
    </div>
</body>
</html>

MvcDemo/Views/ExaminationInformation/Details.cshtml
@model MvcDemo.Models.EIList

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.name-详细信息</title>
</head>
<body>
    <fieldset>
        <legend>@ViewBag.name-详细信息</legend>
    
        
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.DisciplineName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.DisciplineName)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.ExaminationTime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ExaminationTime)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Fraction)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Fraction)
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("修改", "Edit", new { id=Model.Id }) |
        @Html.ActionLink("返回上一级", "Index?Id=" + Model.StudentId)
    </p>
</body>
</html>

MvcDemo/Views/ExaminationInformation/Edit.cshtml
@model MvcDemo.Models.ExaminationInformation

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.name-成绩编辑</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>@ViewBag.name-成绩编辑</legend>
    
            @Html.HiddenFor(model => model.Id)
    
            <div style="display:none">
                @Html.LabelFor(model => model.StudentId)
            </div>
            <div style="display:none">
                @Html.EditorFor(model => model.StudentId)
                @Html.ValidationMessageFor(model => model.StudentId)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Discipline)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.Discipline, ViewBag.DisciplineCode as IEnumerable<SelectListItem>, new { @style = "width:150px;" })
                @Html.ValidationMessageFor(model => model.Discipline)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ExaminationTime)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ExaminationTime)
                @Html.ValidationMessageFor(model => model.ExaminationTime)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Fraction)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Fraction)
                @Html.ValidationMessageFor(model => model.Fraction)
            </div>
    
            <p>
                <input type="submit" value="保存" />
            </p>
        </fieldset>
    }
    
    <div>
        <a target="_self" href="~/ExaminationInformation/Index/@ViewBag.studentId">返回成绩列表</a>
    </div>
</body>
</html>

MvcDemo/Views/ExaminationInformation/Index.cshtml
@model IEnumerable<MvcDemo.Models.EIList>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.name-考试成绩列表</title>
    <style type="text/css">
        #tbList {
            border: 1px solid #0094ff;
            width: 600px;
            margin: 10px auto;
            border-collapse: collapse;
        }

            #tbList th, td {
                border: 1px solid #0094ff;
                padding: 10px;
            }

        .tds {
            border: none;
            padding: 5px;
        }
    </style>
    <script type="text/javascript">
        function del(UserCode)
        {
            if (confirm("是否删除?"))
            {

                eval("document.all.d" + UserCode + ".click()");
            }
        }
        function Details(UserCode)
        {
            self.location.href = "../Details/" + UserCode;
        }
       
    </script>
</head>
<body>
    <p>
        <a target="_self" href="../Create/@ViewBag.id">添加考试成绩</a> | @Html.ActionLink("学生管理", "Index", "StudentInformation")
           </p>
    <table>
        <tr>
            <th style="display:none">
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisciplineName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExaminationTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fraction)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td style="display:none">
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DisciplineName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExaminationTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fraction)
            </td>
            <td>
                <table>
                    <tr>
                        <td class="tds">
                            @using (Html.BeginForm("Edit", "ExaminationInformation", FormMethod.Get))
                            {
                                
                                <span style="display:none"> <input type="text" id="Id" name="Id" value="@Html.DisplayFor(modelItem => item.Id)" /></span>
                                <input type="submit" value="修改" />
                            }
                        </td>
                        <td class="tds">
                            |
                        </td>
                        <td class="tds">
                            @* @Html.ActionLink("Details", "Details", new { UserCode = item.UserCode })*@
                            <input type="button" style="width:100px;height:30px" onclick="Details('@Html.DisplayFor(modelItem => item.Id)')" value="查看详细信息" />
                        </td>
                        <td class="tds"> |</td>
                        <td class="tds">
                            @*@Html.ActionLink("Delete", "Delete", new { id=item.UserCode })*@

                            <input type="button" style="width:40px;height:30px" onclick="del('@Html.DisplayFor(modelItem => item.Id)')" value="删除" />
                            @using (Html.BeginForm("Delete", "ExaminationInformation", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <span style="display:none">
                                    @*@Html.TextBox("StudentId", item.StudentId)*@
                                    <input type="text" id="Id" name="Id" value="@Html.DisplayFor(modelItem => item.Id)" />
                                    ><input type="submit" id="@ViewBag.cid@item.Id" value="Delete" />
                                </span>
                            }
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    }
    
    </table>
</body>
</html>