MvcDemo/Models/Users.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [Display(Name = "用户姓名")]
        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "用户名长度在2位到20位之间。")]
        public string UserName { get; set; }
        [Key]
        [Display(Name = "登陆名")]
        [Required]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "登陆名长度在8位到20位之间。")]
        public string UserCode { get; set; }
        [Display(Name = "密码")]
        [Required]
        [StringLength(30, MinimumLength = 8, ErrorMessage = "密码长度在8位到30位之间。")]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }
        [Display(Name = "性别")]
        public string Sex { get; set; }
    }
}

MvcDemo/Controllers/StudentInformationController.cs
using MvcDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;
using MvcDemo.CS;

namespace MvcDemo.Controllers
{
    public class StudentInformationController : Controller
    {
        //
        // GET: /StudentInformation/
        private htgisEntities1 db = new htgisEntities1();
        /// <summary>
        /// 学生信息加载
        /// </summary>
        /// <param name="Dp">系别</param>
        /// <param name="SearchString">姓名</param>
        /// <returns>默认显示全部</returns>
        [MemberValidation]
        public ActionResult Index(string Dp, string SearchString)
        {
            //查询代码表系别分类并赋值给View的系别DropDownList
            var Dp1 = from d in db.Code
                       where 
                     d.Type=="系别"
                           orderby d.Name                         
                           select new
                           {
                               d.Name
                           };


            ViewBag.Dp = new SelectList(Dp1,"Name","Name");

            //将linq查询内容赋给非数据库实体类
            IQueryable<STList>  AdList = from a in db.StudentInformation
                     from b in db.Code
                     where
                       a.Department == b.Id
                     orderby
                       b.Name,
                       a.Name
                               select new STList
                     {
                         Id=a.Id,
                         Name=a.Name,
                         Sex=a.Sex,
                         DepartmentName = b.Name,
                         EntranceTime=a.EntranceTime
                     };
            //由于ID是数字所以生成删除等按钮时input的ID位数字会发生找不到的问题。
            ViewBag.id = "d";
            //判读是否有查询条件
            if (!String.IsNullOrEmpty(SearchString))
            {
                AdList = AdList.Where(s => s.Name.Contains(SearchString));
            }
            //判读是否有查询条件
            if (string.IsNullOrEmpty(Dp))
                return View(AdList.ToList());
            else
            {
                return View(AdList.Where(x => x.DepartmentName == Dp));
            }

           // return View(AdList.ToList());
        }
        /// <summary>
        /// 创建
        /// </summary>
        /// <returns></returns>
        [MemberValidation]
        public ActionResult Create()
        {
            //查询代码表系别分类并赋值给View的系别DropDownList
            var dcode = from Code in db.Code
                        where
                          Code.Type == "系别"
                        orderby
                          Code.Name
                        select new
                        {
                            Code.Name,
                            Code.Id
                        };
            //设置 DropDownList的VALUE和TEXT
            ViewBag.DepartmentCode = new SelectList(dcode, "Id", "Name");

            //设置默认值
            StudentInformation st = new StudentInformation();
            st.Sex = "1";
            st.Department = 1;
            st.EntranceTime = System.DateTime.Now;
            return View(st);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentInformation st)
        {
            db.StudentInformation.Add(st);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {
            StudentInformation st = db.StudentInformation.Find(Id);
            db.StudentInformation.Remove(st);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// 详细信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {

            IQueryable<STList> AdList = from a in db.StudentInformation
                                        from b in db.Code
                                        where
                                          a.Department == b.Id && a.Id==id
                                        orderby
                                          b.Name,
                                          a.Name
                                        select new STList
                                        {
                                            Id = a.Id,
                                            Name = a.Name,
                                            Sex = a.Sex,
                                            DepartmentName = b.Name,
                                            EntranceTime = a.EntranceTime
                                        };
           STList st = new STList();
          
           if (AdList.Count() > 0)
           {
               st = AdList.ToList()[0];
           }
           else
           {
               return HttpNotFound();
           }
            return View(st);
        }
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="id">学生信息的唯一ID值</param>
        /// <returns></returns>
        public ActionResult Edit(int id = 0)
        {
            //查询代码表系别分类并赋值给View的系别DropDownList
            var dcode = from Code in db.Code
                        where
                          Code.Type == "系别"
                        orderby
                          Code.Name
                        select new
                        {
                            Code.Name,
                            Code.Id
                        };
            ViewBag.DepartmentCode = new SelectList(dcode, "Id", "Name");
            StudentInformation st = db.StudentInformation.Find(id);
            if (st == null)
            {
                return HttpNotFound();
            }
            
            return View(st);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StudentInformation st)
        {
            if (ModelState.IsValid)
            {

                
                    db.Entry(st).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
            }
            return View(st);
        }
    }
}

MvcDemo/Controllers/UsersController.cs
using MvcDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;


namespace MvcDemo.Controllers
{
    public class UsersController : Controller
    {
        //
        // GET: /Users/
        private htgisEntities1 db = new htgisEntities1();
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }
        /// <summary>
        /// 创建用户，因为需要输入确认密码，所以新建一个非数据库实体Register加入确认密码
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            Register register = new Register();
            register.Sex = "1";
            return View(register);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Register register)
        {
            //判读登录名是否重复，其实不用因为这个事主键，但是我给大家演示提交后判读验证值得方法
            var user = from Users in
                           (from Users in db.Users
                            where
                              Users.UserCode == register.UserCode
                            select new
                            {
                                Dummy = "x"
                            })
                       group Users by new { Users.Dummy } into g
                       select new
                       {
                           c = g.Count()
                       };
            if (user.Count() > 0)
            {

                if (user.ToList()[0].c > 0)
                {
                    ViewBag.uc = "登陆名重复请重输。";
                    return View(register);
                }

            }
            //将register的值赋给Users并保存到数据库
            Users u = new Users();
            u.UserCode=register.UserCode;
            u.UserName = register.UserName;
            u.PassWord = register.PassWord;
            u.Sex = register.Sex;
            db.Users.Add(u);
            db.SaveChanges();
            //添加完成跳转到Index方法
            return RedirectToAction("Index");
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string UserCode)
        {
            Users users = db.Users.Find(UserCode);
            db.Users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(string UserCode = null)
        {
            Users users = db.Users.Find(UserCode);
            if (users == null)
            {
                return HttpNotFound();
            }
            Register register = new Register();
            register.UserCode = users.UserCode;
            register.UserName = users.UserName;
            register.Sex = users.Sex;
            return View(register);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Register register)
        {
            if (ModelState.IsValid)
            {

                List<Users> userS = (from Users in db.Users
                                     where
                                       Users.UserCode == register.UserCode
                                     select Users).ToList();
                if (userS.Count > 0)
                {
                    Users user = userS[0];
                    user.UserName = register.UserName;
                    user.PassWord = register.PassWord;
                    user.Sex = register.Sex;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
               
            }
            return View(register);
        }
        public ActionResult Details(string id)
        {
            Users users=db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

    }
   
}

MvcDemo/Views/Users/Create.cshtml
@model MvcDemo.Models.Register

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>创建用户</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>新用户注册</legend>
    <div>@if(ViewBag.uc!=null)
         { 
             <p>@ViewBag.uc</p>
         }
             </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.UserName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.UserName)
                @Html.ValidationMessageFor(model => model.UserName)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.UserCode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.UserCode)
                @Html.ValidationMessageFor(model => model.UserCode)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.PassWord)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PassWord)
                @Html.ValidationMessageFor(model => model.PassWord)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ConfirmPassword)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ConfirmPassword)
                @Html.ValidationMessageFor(model => model.ConfirmPassword)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Sex)
            </div>
            <div class="editor-field">
                @*@Html.EditorFor(model => model.Sex)*@
                @Html.RadioButtonFor(model => model.Sex, "1", new { @id = "radio1", @name = "Status" })<label>男</label>
                @Html.RadioButtonFor(model => model.Sex, "0", new { @id = "radio2", @name = "Status" })<label>女</label>
                @*@Html.RadioButton("男","1",true)*@
                @Html.ValidationMessageFor(model => model.Sex)
            </div>
    
            <p>
                <input type="submit" value="注册" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("返回用户列表", "Index")
    </div>
    
</body>
</html>

MvcDemo/Views/Users/Details.cshtml
@model MvcDemo.Models.Users

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>详细信息</title>
</head>
<body>
    <fieldset>
        <legend>详细信息</legend>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.UserName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.UserName)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.PassWord)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.PassWord)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Sex)
        </div>
        <div class="display-field">
           @if(Model.Sex=="1")
           { 
               <p>男</p>
           }
           else
           { 
        <p>女</p>
           }
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("修改", "Edit", new { UserCode = Model.UserCode }) |
        @Html.ActionLink("返回用户列表", "Index")
    </p>
</body>
</html>

MvcDemo/Views/Users/Edit.cshtml
@model MvcDemo.Models.Register

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>修改用户信息</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>修改用户信息</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.UserName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.UserName)
                @Html.ValidationMessageFor(model => model.UserName)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.UserCode)
            </div>
            <div class="editor-field">
                @Html.DisplayTextFor(model => model.UserCode)
</div>
        @*    @Html.HiddenFor(model => model.UserCode)*@
    
            <div class="editor-label">
                @Html.LabelFor(model => model.PassWord)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PassWord)
                @Html.ValidationMessageFor(model => model.PassWord)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ConfirmPassword)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ConfirmPassword)
                @Html.ValidationMessageFor(model => model.ConfirmPassword)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Sex)
            </div>
            <div class="editor-field">
                @Html.RadioButtonFor(model => model.Sex, "1", new { @id = "radio1", @name = "Status" })<label>男</label>
                @Html.RadioButtonFor(model => model.Sex, "0", new { @id = "radio2", @name = "Status" })<label>女</label>
                @Html.ValidationMessageFor(model => model.Sex)
            </div>
    
            <p>
                <input type="submit" value="保存" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("返回用户列表", "Index")
    </div>
</body>
</html>

MvcDemo/Views/Users/Index.cshtml
@model IEnumerable<MvcDemo.Models.Users>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <style type="text/css">
        #tbList {
            border: 1px solid #0094ff;
            width: 600px;
            margin: 10px auto;
            border-collapse: collapse;
        }

            #tbList th, td {
                border: 1px solid #0094ff;
                padding: 10px;
            }
        .tds {
            border:none;
            padding:5px;
        }
    </style>

    <meta name="viewport" content="width=device-width" />
    <title>用户列表</title>
    <script type="text/javascript">
        function del(UserCode)
        {
            if (confirm("是否删除?"))
            {
                
                eval("document.all." + UserCode + ".click()");
            }
        }
        function Details(UserCode)
        {
            self.location.href = "./Users/Details/" + UserCode;
        }
    </script>
</head>
<body>
    <p>
        @Html.ActionLink("创建新用户", "Create") | @Html.ActionLink("学生管理", "Index", "StudentInformation")
    </p>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassWord)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sex)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserCode)
            </td>
            <td>
               ******
            </td>
            <td>
               @if (item.Sex == "1")
               {
                   <p>男</p>
               }
               else
               {
                <p>女</p>
               }
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { UserCode = item.UserCode }) |*@
                <table>
                    <tr>
                        <td class="tds">
                            @using (Html.BeginForm("Edit", "Users", FormMethod.Get))
                            {
                                <span style="display:none"> @Html.TextBox("UserCode", item.UserCode)</span>
                                <input type="submit" value="修改" />
                            }
                        </td>
                        <td class="tds">
                            |
                        </td>
                        <td class="tds">
                           @* @Html.ActionLink("Details", "Details", new { UserCode = item.UserCode })*@
                            <input type="button" style="width:100px;height:30px" onclick="Details('@item.UserCode')" value="查看详细信息" />
                        </td>
                        <td class="tds"> |</td>
                        <td class="tds">
                            @*@Html.ActionLink("Delete", "Delete", new { id=item.UserCode })*@

                            <input type="button" style="width:40px;height:30px" onclick="del('@item.UserCode')" value="删除" />
                            @using (Html.BeginForm("Delete", "Users", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <span style="display:none">

                                    @Html.TextBox("UserCode", item.UserCode)
                                    <input type="submit" id="@item.UserCode" value="Delete" />
                                </span>
                            }
                        </td> 
</tr>
                </table>
            </td>
        </tr>
    }
    
    </table>
</body>
</html>